# Generated by Django 3.1.8 on 2022-12-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlmodel',
            name='format',
            field=models.CharField(choices=[('h5', 'H5'), ('h5r', 'H5R'), ('pkl', 'Pickle')], max_length=50, verbose_name="Model's format"),
        ),
    ]
