# Generated by Django 4.1.3 on 2022-12-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_traineddataset_alter_facerecognition_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50, verbose_name="Model's name")),
                ('model_format', models.CharField(max_length=50, verbose_name="Model's format")),
                ('model_timestamp', models.DateTimeField(auto_now_add=True)),
                ('model_file', models.FileField(upload_to='models/')),
            ],
        ),
        migrations.RemoveField(
            model_name='traineddataset',
            name='predicted_age',
        ),
        migrations.RemoveField(
            model_name='traineddataset',
            name='predicted_gender',
        ),
        migrations.AddField(
            model_name='traineddataset',
            name='pickle_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
