# Generated by Django 3.1.8 on 2022-12-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_model_file_mlmodel_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Model's name")),
                ('format', models.CharField(max_length=50, verbose_name="Model's format")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='currentModel/')),
            ],
        ),
        migrations.CreateModel(
            name='DatasetElementFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=124)),
            ],
        ),
        migrations.AlterField(
            model_name='facerecognition',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mlmodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='traineddataset',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='trainingdatasetfile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
