# Generated by Django 4.1.3 on 2022-12-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_model_file_mlmodel_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Model's name")),
                ('format', models.CharField(max_length=50, verbose_name="Model's format")),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='currentModel/')),
            ],
        ),
    ]
