# Generated by Django 3.1.8 on 2022-12-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='Dataset',
        ),
        migrations.RemoveField(
            model_name='traineddataset',
            name='pickle_file',
        ),
        migrations.AddField(
            model_name='traineddataset',
            name='file',
            field=models.FileField(default='default.zip', upload_to='dataset/data'),
        ),
        migrations.AddField(
            model_name='traineddataset',
            name='filename',
            field=models.CharField(default='filename', max_length=100, verbose_name='filename'),
        ),
    ]
