# Generated by Django 3.1.8 on 2022-12-27 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221227_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='existingPath',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='name',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='eof',
        ),
    ]
