# Generated by Django 3.1.8 on 2023-01-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20230103_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facerecognition',
            name='predictions',
        ),
        migrations.AddField(
            model_name='facerecognition',
            name='results',
            field=models.JSONField(default='-'),
        ),
    ]
