# Generated by Django 4.1.3 on 2022-12-05 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_mlmodel_remove_traineddataset_predicted_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_format',
            new_name='format',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='mlmodel',
            old_name='model_timestamp',
            new_name='timestamp',
        ),
    ]
