# Generated by Django 3.1.8 on 2022-11-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FacePicture', '0002_auto_20221128_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facepicture',
            options={},
        ),
        migrations.RemoveField(
            model_name='facepicture',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='facepicture',
            name='id',
        ),
        migrations.AlterField(
            model_name='facepicture',
            name='filename',
            field=models.CharField(max_length=72, primary_key=True, serialize=False),
        ),
    ]
